### ISSUE TITLE
contain: outside is not guaranteed on zoom

### ISSUE THREAD

**Issue by partiellkorrekt** [timmywil/panzoom#426]
### Subject of the issue

When you zoom programatically for an element that's set to ```contain: outside```, it is not quaranteed that it covers it's parent completely after that.

### Your environment

- Version of panzoom: current (built from master on September 14th 2019)
- Chrome 78 (other browsers are affected as well)

### Expected behaviour

After any zoom-operation the element should still cover it's parent completely

### Actual behaviour

The element doesn't update it's offset so it might not cover it's complete parent

### Steps to reproduce

See this fiddle: [https://jsfiddle.net/a8jh79rp/5/](https://jsfiddle.net/a8jh79rp/5/)

After you click on the button the image will be offset. The button does the following:
1. scale the image
2. move it
3. scale it back

Sometimes it will also be offset after you zoom with the mousewheel

**Comment by partiellkorrekt** [comment]
An easy workaround as a user is to add the following code after you call panzoom.zoom():
```js
const { x, y } = panzoom.getPan()
panzoom.pan(x, y)
```

See [https://jsfiddle.net/a8jh79rp/7/](https://jsfiddle.net/a8jh79rp/7/)

**Comment by timmywil** [comment]
I just pushed a fix to the master branch that will set the `minScale` and `maxScale` options based on the `contain` option, if present. Give that a try and let me know if it works for you.

**Comment by partiellkorrekt** [comment]
I can confirm that this fixes the bug with programmatic zoom for me. 👍

But I can still trigger this bug with mouse-events. I created a new fiddle for this: [https://jsfiddle.net/qrmst6ky/3/](https://jsfiddle.net/qrmst6ky/3/) 

To trigger the bug you can click on "Show me the other problem".

Btw.: The minification fails for me with the latest version of this git. That's why I inserted the unminified code.

**Comment by partiellkorrekt** [comment]
This bug also occurs, if you try to programmatically zoom after the user has zoomed with the mouseweel.

See: [https://jsfiddle.net/qrmst6ky/5/](https://jsfiddle.net/qrmst6ky/5/)

Button 1 demonstrates resetting the zoomlevel programatically after the user has zoomed by wheel
Button 2 demonstrates zooming by wheel and then zooming back

**Comment by timmywil** [comment]
The minification is fixed on master. Working on the other issue.

**Comment by timmywil** [comment]
I see what I did wrong. I trusted my old self and I think my old self was just wrong. :O

Hopefully that fixes it now. I tested your fiddles after pasting the new code in and it seems ok.

Thanks for opening this issue.

**Comment by partiellkorrekt** [comment]
I am so sorry, but this issue is not completely fixed. When you zoom in very close and then reset the zoom to 1, this bug still occurs. See [https://jsfiddle.net/6vqp8brt/](https://jsfiddle.net/6vqp8brt/)

**Comment by timmywil** [comment]
No need to be sorry. Thanks for testing.

**Comment by timmywil** [comment]
I see it now in the demo. Zoom in -> pan all the way one way -> Zoom out. It has to do with my use of Math.max. If the pan value for an axis is negative, it does not normalize to zero. When the pan value is positive, everything is fine.

**Comment by timmywil** [comment]
Nevermind, it has to do with when the scale is set. Apparently, old self was half right.

**Comment by timmywil** [comment]
Let's give this one more try. The master branch is updated. Thanks for your patience and continuing to test with me. This has been a finicky bug.

**Comment by timmywil** [comment]
Your test case updated seems to work https://jsfiddle.net/fr0y7avw/

**Comment by timmywil** [comment]
I tried this test case as well https://jsfiddle.net/aefb2mq0/

At first, I thought it was bugged again, but in order for me to use `getBoundingClientRect` and avoid layout thrashing, when you set zoom programmatically, you have to allow for it to paint and update the dimensions before you can pan again and have it properly contain the x/y values.

In other words, I added a `setTimeout` around the call to `pan`. https://jsfiddle.net/aefb2mq0/

**Comment by timmywil** [comment]
I did notice an issue with the second example, but I think it again has to do with the scale getting painted before calling zoom. See https://jsfiddle.net/8om096kn/.

**Comment by timmywil** [comment]
I've added a note to the README about the need to paint https://github.com/timmywil/panzoom#a-note-on-the-async-nature-of-panzoom

**Comment by timmywil** [comment]
I know I could work around this by using `offsetWidth` instead and ignore the transform. That would probably be more consistent, but it would come at the cost of constant layout thrashes and performance issues. I'd like to stick with `getBoundingClientRect`. Waiting for a paint seems like a worthy trade-off.

**Comment by partiellkorrekt** [comment]
The current version of this repository fixes the bug for me :) Thanks for your support!
